## Basic Python Scripts

*Vishal Pranav* - **GCTC1918147**

## 1. Split String

In [1]:
S = "Hi there, Robert!"

L = S.split(" ")

print(L)

['Hi', 'there,', 'Robert!']


## 2. Use .format() to print the following string.

In [2]:
planet = "Earth"
diameter = 12742

print(f"The diameter of { planet } is { diameter } kilometers")

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [3]:
d = { 'k1': [ 1, 2, 3, { 'tricky': [ 'oh', 'man', 'inception', { 'target': [ 1, 2, 3, 'hello' ] } ] } ] }

print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [7]:
zero = np.zeros(10)
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
five = np.ones(10)*5
print(five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
even = np.arange(20, 35, 2)
print(even)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
mat = np.arange(0, 9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate arrays a and b 


In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

con = np.concatenate((a, b), axis = None)
print(con)

[1 2 3 4 5 6]


# Pandas

In [18]:
import pandas as pd

## 8. Create a dataframe with 3 rows and 2 columns

In [23]:
names = [ "Robert", "Chris", "Harris" ]
age = [ 23, 21, 24 ]

result = pd.DataFrame()
result["name"] = names
result["age"] = age
print(result)

     name  age
0  Robert   23
1   Chris   21
2  Harris   24


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
dates = pd.date_range(start = "01-01-2023", end = "02-10-2023")
print(dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [25]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

result = pd.DataFrame(lists, columns=[ str(col + 1) for col in range(len(lists[0])) ])
print(result)

   1    2   3
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
